language: node_js

node_js:
  - '14'

before_install:
- rvm install 2.7.0
- curl -o- -L https://yarnpkg.com/install.sh | bash

before_script:
  # install dependencies
  # travis runs `yarn install` when yarn.lock exists

  # install ruby dependencies
  - gem install bundler
  - bundle install
  - yarn build
