# Site settings
language:               "de"
languages:              ["de", "en"]
title:                  "NYC Musikmarathon Mattighofen"
slogan:                 "Live music &mdash; with live music."
description:            "»NYCMM« bietet ein Musikseminar, Konzerte und Jam-Sessions wo du Musik machen und genießen kannst."
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

# keep in mind that jekyll is going to exclude this files in jekyll build task from gulp.
exclude:
  - "assets/js/lib/"
  - "assets/scss/"
  - "assets/js/app.js"
  - "composer.json"
  - "composer.lock"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"
  - "yarn-error.log"
  - "nycmm.code-workspace"

# if there are extra generated files (such as bundle.js from webpack or minified app.cs) we have to let
# jekyll know about it, otherwise it will delete them
keep_files:
  - "assets/js/bundle.js"
  - "assets/css/app.css"

# Plugins
# Add plugins in the Gemfile
plugins:
  - jekyll-paginate

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# header video
header_video:     "/assets/video/bassmovie_x264_blur.mp4"
header_image:     ""

# logo
logo_white:       "/assets/img/logo_white.png"

# Outputting
permalink:        "/blog/:year/:title/"
paginate_path:    "/blog/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

highlighter: rouge

# See _data/authors.yml
author: matt

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: matt     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: false
      author: matt     # Default author for posts
